version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - api
