FROM node:20-alpine as builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist
# Копирование .env файла - опционально, лучше использовать переменные окружения
# COPY --from=builder /app/.env ./.env

RUN npm ci --only=production

# Аргумент для определения команды запуска
ARG PORT=3000
ENV PORT=$PORT
EXPOSE $PORT

CMD ["node", "dist/index.js"] 