version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  bot:
    build: ./bot
    restart: unless-stopped
    depends_on:
      - api
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge